### ISSUE TITLE
Bug : When I am trying to signup with Oauth its showing you do not have permission to do that.

### ISSUE THREAD

**Issue by ramesh-dada** [v17development/flarum-third-party-login-only#3]
When I am trying to signup with Oauth its showing you do not have permission to do that.
![image](https://user-images.githubusercontent.com/75124237/130225029-5db3023f-d4e6-4574-a836-9bb5116acb6b.png)

**Comment by Hari-Bonda** [comment]
@ramesh-dada is this issue resolved for you? can you DM via discord?

**Comment by ramesh-dada** [comment]
Yeah it's resolved in the latest version..
